<?xml version="1.0" encoding="utf-8"?><Database Name="BizzyQuote" Class="BizzyQuoteDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost;Initial Catalog=BizzyQuote;Integrated Security=True" SettingsObjectName="BizzyQuote.Data.Properties.Settings" SettingsPropertyName="BizzyQuoteConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CompanyID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastLoggedIn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="User_Quote" Member="Quotes" ThisKey="ID" OtherKey="EmployeeID" Type="Quote" />
      <Association Name="Company_User" Member="Company" ThisKey="CompanyID" OtherKey="ID" Type="Company" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Images" Member="Images">
    <Type Name="Image">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="QuoteID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ImageURL" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Notes" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="Quote_Image" Member="Quote" ThisKey="QuoteID" OtherKey="ID" Type="Quote" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Material" Member="Materials">
    <Type Name="Material">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="SubName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Measurement" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Material_QuoteItem" Member="QuoteItems" ThisKey="ID" OtherKey="MaterialID" Type="QuoteItem" />
    </Type>
  </Table>
  <Table Name="dbo.MaterialProduct" Member="MaterialProducts">
    <Type Name="MaterialProduct">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Measurement" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="MaterialProduct_QuoteItem" Member="QuoteItems" ThisKey="ID" OtherKey="MaterialProductID" Type="QuoteItem" />
    </Type>
  </Table>
  <Table Name="dbo.QuoteItem" Member="QuoteItems">
    <Type Name="QuoteItem">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="QuoteID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaterialProductID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Measurement" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaterialID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Height" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="Width" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="LinealFt" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="SquareFt" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="Dollars" Type="System.Decimal" DbType="Decimal(15,2)" CanBeNull="true" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(15,2)" CanBeNull="true" />
      <Association Name="Material_QuoteItem" Member="Material" ThisKey="MaterialID" OtherKey="ID" Type="Material" IsForeignKey="true" />
      <Association Name="MaterialProduct_QuoteItem" Member="MaterialProduct" ThisKey="MaterialProductID" OtherKey="ID" Type="MaterialProduct" IsForeignKey="true" />
      <Association Name="Quote_QuoteItem" Member="Quote" ThisKey="QuoteID" OtherKey="ID" Type="Quote" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Quote" Member="Quotes">
    <Type Name="Quote">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="CompanyID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.Decimal" DbType="Decimal(15,2)" CanBeNull="true" />
      <Column Name="Notes" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="Quote_Image" Member="Images" ThisKey="ID" OtherKey="QuoteID" Type="Image" />
      <Association Name="Quote_QuoteItem" Member="QuoteItems" ThisKey="ID" OtherKey="QuoteID" Type="QuoteItem" />
      <Association Name="User_Quote" Member="User" ThisKey="EmployeeID" OtherKey="ID" Type="User" IsForeignKey="true" />
      <Association Name="Company_Quote" Member="Company" ThisKey="CompanyID" OtherKey="ID" Type="Company" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Company" Member="Companies">
    <Type Name="Company">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Zip" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Company_User" Member="Users" ThisKey="ID" OtherKey="CompanyID" Type="User" />
      <Association Name="Company_Quote" Member="Quotes" ThisKey="ID" OtherKey="CompanyID" Type="Quote" />
    </Type>
  </Table>
</Database>